[package]
name = "jwt-helper"
version = "0.1.0"
authors = ["Aaron Goodfellow"]

[dependencies]
jsonwebtoken = "5"
serde_derive = "1"
serde = "1"
base64 = "0.10.1"
clap = {version = "2", features = ["yaml"]}